# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on ref creation (branch, tag)
  push:
    tags:
      - v[0-9]+.[0-9]+.?[0-9]?**
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_release:
    # The type of runner that the job will run on

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Give rigths to run a script from repository
        run: chmod +x -R ./scripts/

      #Need this because the tag that triggers workflow applies on the branch as lightweight,
      # see [https://github.com/actions/checkout/issues/290]
      - name: Fetch all tags
        run: git fetch --tags --force

      - name: Get latest release tag
        run: |
          export RELEASE_VERSION=$(./scripts/releaseTag.sh)
          echo "RELEASE_VERSION=$RELEASE_VERSION"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Get release name
        run: |
          export RELEASE_CODENAME=$(git for-each-ref --format="%(subject)" "refs/tags/${{ env.RELEASE_VERSION }}")
          export RELEASE_NAME="$(./scripts/release/genReleaseName.sh ./config/main.json ${{ env.RELEASE_VERSION }}) - \"$RELEASE_CODENAME\""
          echo "RELEASE_NAME=$RELEASE_NAME"
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "RELEASE_CODENAME=$RELEASE_CODENAME" >> $GITHUB_ENV

      - name: Print release version
        run: |
          echo 'Создаем релиз ${{ env.RELEASE_VERSION }}'
          echo $(git for-each-ref "refs/tags/${{ env.RELEASE_VERSION }}")

      - name: Get previous release tag
        run: |
          export PREV_RELEASE=$(./scripts/prevRelease.sh ${{ env.RELEASE_VERSION }})
          echo "PREV_RELEASE=$PREV_RELEASE"
          echo "PREV_RELEASE=$PREV_RELEASE" >> $GITHUB_ENV

      - name: Launch release
        env:
          TOKEN: ${{ secrets.test_token }}
          ORG_ID: ${{ secrets.org_id }}
        run: ./scripts/release/release.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build_docker_image:
    needs: create_release

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
    
      - name: Build image
        env:
          TOKEN: ${{ secrets.test_token }}
          ORG_ID: ${{ secrets.org_id }}
        run: ./scripts/docker/buildDocker.sh

  run_tests:
    needs: create_release

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
    
      - name: Launch tests
        env:
          TOKEN: ${{ secrets.test_token }}
          ORG_ID: ${{ secrets.org_id }}
        run: ./scripts/test/launchTests.sh